### ISSUE TITLE
Show custom breadcrumb for parent pages.

### ISSUE THREAD

**Issue by GaryJones** [GaryJones/genesis-single-breadcrumbs#2]
When you have parent pages, the custom breadcrumb you changed for the parent page doesn't come up. The title does.

**Comment by deckerweb** [comment]
There seem to be some issues still -- for pages...
1) When displaying a child page, the default breadcrumb shows for the child, but for parent it's empty/missing...
2) Adding a custom crumb for parent brings it do display, but then child crumb is empty/missing...
3) Adding both custom crumbs for parent & child brings both to display...

**Comment by deckerweb** [comment]
Sorry, even have to correct the above:
for 1) when viewing child page, both crumbs are empty/missing (but seperator is showing)

new 4) When viewing a parent page, its default crumb is showing so far

**Comment by GaryJones** [comment]
Thanks David - just forgot to do the page title as the fallback when no custom breadcrumb title is found.
