### ISSUE TITLE
Feature Request: Change to "Enable..." when breadcrumbs are globally disabled

### ISSUE THREAD

**Issue by cgrymala** [GaryJones/genesis-single-breadcrumbs#4]
If breadcrumbs are disabled through Genesis -> Theme Settings, it would be nice for this plugin to change its behavior to allow you to enable them on specific pages. I have a site where we only want breadcrumbs within one specific sub-section of the site, and it would be a lot faster & simpler for us to turn them on where we want them than it would be to turn them on globally, then go through all of the other pages and disable them with this plugin. Thanks.

**Comment by GaryJones** [comment]
Nice suggestion, thanks!
